sudo: required

language: cpp

dist: trusty

compiler: gcc

os:
- linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports
    packages:
    - cmake
    - cmake-data
    - gcc-7
    - g++-7

script:
- mkdir build
- cd build
- cmake --version
- ${DEPS_DIR}/cmake/bin/cmake .. && make