sudo: required

language: cpp

dist: trusty

compiler: gcc

os:
- linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - george-edison55-precise-backports
    packages:
    - cmake
    - cmake-data
    - gcc-7
    - g++-7
    - xorg-dev

install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 60
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60

script:
- mkdir build
- cd build
- cmake --version
- cmake .. && make