matrix:
  include:
    - sudo: required
      language: cpp
      dist: trusty
      os:
      - linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - cmake
          - cmake-data
          - gcc-7
          - g++-7
          - xorg-dev
      script:
      - mkdir build
      - cd build
      - cmake --version
      - cmake .. && make

    - sudo: required
      language: cpp
      dist: trusty
      os:
      - linux
      addons:
        apt:
          sources:
          - llvm-toolchain-trusty-5.0
          - george-edison55-precise-backports
          packages:
          - cmake
          - cmake-data
          - clang-5.0
          - xorg-dev
      script:
      - mkdir build
      - cd build
      - cmake --version
      - cmake .. && make

    - sudo: required
      language: node_js
      dist: trusty
      os:
      - linux
      node_js:
      - node
      services:
      - docker
      before_install:
      - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash
      script:
      - docker exec -it emscripten emconfigure cmake .
      - docker exec -it emscripten emmake make