matrix:
  include:
    - name: ubuntu 14.04 gcc-7 build
      sudo: false
      language: cpp
      dist: trusty
      os:
      - linux
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - george-edison55-precise-backports
          packages:
          - cmake
          - cmake-data
          - gcc-7
          - g++-7
          - xorg-dev
      script:
      - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake .
      - cmake --build .

    - name: ubuntu 14.04 clang-5 build
      sudo: false
      language: cpp
      dist: trusty
      os:
      - linux
      addons:
        apt:
          sources:
          - llvm-toolchain-trusty-5.0
          - george-edison55-precise-backports
          packages:
          - cmake
          - cmake-data
          - clang-5.0
          - xorg-dev
      script:
      - CXX=/usr/bin/clang++-5.0 CC=/usr/bin/clang-5.0 cmake .
      - cmake --build .

    - name: emscripten 1.38.12-64bit build
      sudo: required
      language: node_js
      dist: trusty
      os:
      - linux
      node_js:
      - node
      services:
      - docker
      before_install:
      - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-tag-1.38.12-64bit bash
      script:
      - docker exec -it emscripten emconfigure cmake .
      - docker exec -it emscripten emmake make